In [2]:
import pandas as pd

###  Selecione a primeira transação diária de cada cliente

In [6]:

transacoes = pd.read_csv ("../data/transacoes.csv", sep=";")
transacoes

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch
...,...,...,...,...,...
302231,ffff45c7-83dc-4fa9-82b5-b41352093596,6313ceac-7806-4d34-aedd-476eed7c853a,2025-01-03 12:59:27.229,1,twitch
302232,ffff52de-13fb-4405-a797-fddb5b4a48c5,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-24 12:22:26.313,1,twitch
302233,ffffb5ab-047e-43e4-bab3-ee2d19e9b7db,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,2024-08-16 13:09:42.576,1,twitch
302234,ffffc72e-d882-47f0-b933-cfd92c7e6621,2d3d2dce-d353-4961-ad39-46723efe2100,2024-02-06 11:51:24.788,1,twitch
302235,fffff928-9a18-4741-a516-3a92351d1d72,65662aff-44d6-4f06-b9d9-07445c6e5943,2024-08-21 14:13:31.788,1,twitch

In [ ]:
transacoes = transacoes.sort_values("DtCriacao") #ordena
transacoes["data"] = pd.to_datetime(transacoes["DtCriacao"]).dt.date #cria coluna apenas da data
transacoes.drop_duplicates(keep="first", subset=["IdCliente", "data"]) #dropa as mesmas datas e mantem a primeira

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem,data
296733,fb4e3102-6125-414e-b086-e7f641e38f93,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-01-27 11:53:23.774,1,twitch,2024-01-27
203249,ac18e5fd-eb6e-4d83-9bf1-bd8973fcd1b4,2d3d2dce-d353-4961-ad39-46723efe2100,2024-01-29 11:55:05.127,1,twitch,2024-01-29
46108,270948e3-a015-4255-be6a-36010d26b74d,c4f241f8-2140-4f72-b1a3-904fcc51e38c,2024-01-29 11:57:14.602,1,twitch,2024-01-29
7221,060cc463-a074-4c65-867c-bb88606a6123,65662aff-44d6-4f06-b9d9-07445c6e5943,2024-01-29 11:59:41.832,1,twitch,2024-01-29
94651,505b94d7-9bcb-48f1-803d-337245f02c45,03d75a45-0b36-4fd7-a84e-7b36912f1998,2024-01-29 12:00:02.504,1,twitch,2024-01-29
...,...,...,...,...,...,...
287855,f3c800c4-90ef-48b1-974c-efda10334dba,274dba93-004d-4cda-9d77-dd61282f201a,2026-03-06 14:04:03.071,50,twitch,2026-03-06
695,008a818a-7377-45ab-b016-791194ac58f4,6dece871-c22b-40a9-a919-19a88acf3401,2026-03-06 14:25:45.883,1,twitch,2026-03-06
253098,d6644a48-78d7-434c-87b7-82d27cef85e0,f19aaa00-f337-4174-ba14-a2a39dd6ebbf,2026-03-06 14:33:35.827,50,twitch,2026-03-06
101151,55f6d14e-ba85-4252-ae35-d953a3d9c652,3458efb0-0a7e-490f-8856-c29f9050d938,2026-03-06 14:34:58.664,50,twitch,2026-03-06
93921,4fc34bfb-fc99-4ad4-a84d-af7169b60dca,df0cc1e9-f2d0-421b-b018-eadb75bceeaa,2026-03-06 16:38:45.321,1000,cursos,2026-03-06

<class 'pandas.core.frame.DataFrame'>
Index: 302236 entries, 296733 to 93921
Data columns (total 6 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   IdTransacao        302236 non-null  object
 1   IdCliente          302236 non-null  object
 2   DtCriacao          302236 non-null  object
 3   QtdePontos         302236 non-null  int64
 4   DescSistemaOrigem  302236 non-null  object
 5   data               302236 non-null  object
dtypes: int64(1), object(5)
memory usage: 16.1+ MB