In [27]:
import pandas as pd
import os

df_geral = pd.read_csv("data/ipea/homicidios.csv", sep=";")
df_geral.head()

   cod nome  período  valor
0   53   DF     1989    331
1   11   RO     1989    490
2   12   AC     1989     95
3   13   AM     1989    321
4   14   RR     1989    113

In [21]:
# df_geral = df_geral.rename(columns={"valor": "homicidios"})
# df_geral = df_geral.drop(["cod"], axis=1)
# df_geral.head()
def read_file (file_name:str):
    df = (pd.read_csv(f"data/ipea/{file_name}.csv",sep=";").rename(columns={"valor":file_name}).set_index(["nome","período"]).drop(["cod"],axis=1))
    return df

In [23]:
df_negros = read_file("homicidios-negros")
df_negros

              homicidios-negros
nome período
AC   1996                     0
TO   1996                     0
SP   1996                   359
SE   1996                     0
SC   1996                     0
...                         ...
PA   2021                  2611
MT   2021                   672
MS   2021                   388
RS   2021                   456
SC   2021                   172

[702 rows x 1 columns]

In [30]:
files_names = os.listdir("data/ipea/")
files_names

['homicidios-nao-negros.csv',
 'homicidios-de-jovens-mulheres.csv',
 'homicidios-de-homens-por-armas-de-fogo.csv',
 'homicidios.csv',
 'homicidios-de-jovens-homens.csv',
 'homicidios-negros.csv',
 'homicidios-de-mulheres-por-armas-de-fogo.csv',
 'homicidios-por-armas-de-fogo.csv',
 'homicidios-homens.csv',
 'homicidios-mulheres-nao-negras.csv',
 'homicidios-homens-negros.csv',
 'homicidios-mulheres-negras.csv',
 'homicidio-de-jovens-por-armas-de-fogo.csv',
 'homicidios-de-jovens.csv',
 'homicidios-mulheres.csv']

In [31]:
dfs = []
for i in files_names:
    file_name = i.split(".")[0]
    dfs.append(read_file(file_name))

In [32]:
dfs[-3]

              homicidio-de-jovens-por-armas-de-fogo
nome período
DF   1989                                       116
SP   1989                                      1821
RJ   1989                                      1722
ES   1989                                       180
MG   1989                                       223
...                                             ...
TO   2021                                       135
AP   2021                                       217
PA   2021                                      1106
RR   2021                                        58
AM   2021                                       813

[891 rows x 1 columns]

In [36]:
df_full =pd.concat(dfs, axis=1).reset_index().sort_values(["período", "nome"])
df_full

,nome,período,homicidios-nao-negros,homicidios-de-jovens-mulheres,homicidios-de-homens-por-armas-de-fogo,homicidios,homicidios-de-jovens-homens,homicidios-negros,homicidios-de-mulheres-por-armas-de-fogo,homicidios-por-armas-de-fogo,homicidios-homens,homicidios-mulheres-nao-negras,homicidios-homens-negros,homicidios-mulheres-negras,homicidio-de-jovens-por-armas-de-fogo,homicidios-de-jovens,homicidios-mulheres
726,AC,1979,NaN,0,NaN,NaN,14,NaN,NaN,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
714,AL,1979,NaN,6,NaN,NaN,104,NaN,NaN,131,NaN,NaN,NaN,NaN,NaN,NaN,NaN
725,AM,1979,NaN,4,NaN,NaN,80,NaN,NaN,55,NaN,NaN,NaN,NaN,NaN,NaN,NaN
722,AP,1979,NaN,1,NaN,NaN,7,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
712,BA,1979,NaN,17,NaN,NaN,114,NaN,NaN,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
680,RS,2021,1406.0,68,342.0,1889.0,703,456.0,118.0,1379,1656.0,182.0,411.0,45.0,639.0,771.0,230.0
681,SC,2021,530.0,25,238.0,712.0,265,172.0,33.0,375,620.0,79.0,161.0,11.0,180.0,290.0,92.0
688,SE,2021,47.0,14,960.0,790.0,420,742.0,21.0,662,751.0,3.0,707.0,34.0,394.0,435.0,37.0
683,SP,2021,1537.0,86,498.0,3094.0,1007,1505.0,92.0,1648,2742.0,209.0,1373.0,131.0,741.0,1093.0,342.0
698,TO,2021,70.0,12,178.0,441.0,199,355.0,14.0,253,401.0,13.0,333.0,22.0,135.0,211.0,39.0

In [37]:
df_full.to_csv("homicidios_consolidado.csv",index=False, sep= ";")