In [2]:
import pandas as pd
import numpy as np

In [3]:
df_transacoes = pd.read_csv ("data/transacoes.csv", sep=";")
df_transacoes

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch
...,...,...,...,...,...
302231,ffff45c7-83dc-4fa9-82b5-b41352093596,6313ceac-7806-4d34-aedd-476eed7c853a,2025-01-03 12:59:27.229,1,twitch
302232,ffff52de-13fb-4405-a797-fddb5b4a48c5,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-24 12:22:26.313,1,twitch
302233,ffffb5ab-047e-43e4-bab3-ee2d19e9b7db,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,2024-08-16 13:09:42.576,1,twitch
302234,ffffc72e-d882-47f0-b933-cfd92c7e6621,2d3d2dce-d353-4961-ad39-46723efe2100,2024-02-06 11:51:24.788,1,twitch
302235,fffff928-9a18-4741-a516-3a92351d1d72,65662aff-44d6-4f06-b9d9-07445c6e5943,2024-08-21 14:13:31.788,1,twitch

In [4]:
def diff_amp (x: pd.Series):
    amplitude = x.max() - x.min()
    media = x.mean()
    return np.sqrt((amplitude-media)**2)

In [5]:
(df_transacoes.groupby(by=["IdCliente"]).agg({"IdTransacao":['count'],
                                              "QtdePontos": ["sum","mean",diff_amp]})
                                              )

                                     IdTransacao QtdePontos               \
                                           count        sum         mean
IdCliente
000dc0f6-e4f2-4a42-b8cd-b586ed1c709a           2          2     1.000000
000ff655-fa9f-4baa-a108-47f581ec52a1         512      25086    48.996094
001749bd-37b5-4b1e-8111-f9fbba90f530           1         50    50.000000
0019bb9e-26d4-4ebf-8727-fc911ea28a92           2          2     1.000000
0028dda2-334f-40bb-9582-475fb6719471           4       1100   275.000000
...                                          ...        ...          ...
ff1ceaef-650c-422b-bdc3-6984e29e7aa5          15        162    10.800000
ff2cabd3-3316-4b3f-8494-c25f95e90524           8         57     7.125000
ff4909ad-4e52-4767-a6fc-0fbd76e37857           1         50    50.000000
ff5d2399-6b53-49f0-b41e-fdaaa0da172a         385       2021     5.249351
fff7862d-4b2c-4140-a4c5-509b48ed31b4           1       1000  1000.000000


                                         diff_amp
IdCliente
000dc0f6-e4f2-4a42-b8cd-b586ed1c709a     1.000000
000ff655-fa9f-4baa-a108-47f581ec52a1  1451.003906
001749bd-37b5-4b1e-8111-f9fbba90f530    50.000000
0019bb9e-26d4-4ebf-8727-fc911ea28a92     1.000000
0028dda2-334f-40bb-9582-475fb6719471  2625.000000
...                                           ...
ff1ceaef-650c-422b-bdc3-6984e29e7aa5    38.200000
ff2cabd3-3316-4b3f-8494-c25f95e90524    41.875000
ff4909ad-4e52-4767-a6fc-0fbd76e37857    50.000000
ff5d2399-6b53-49f0-b41e-fdaaa0da172a   993.750649
fff7862d-4b2c-4140-a4c5-509b48ed31b4  1000.000000

[3542 rows x 4 columns]