In [ ]:
import pandas as pd
import sqlalchemy

engine = sqlalchemy.create_engine("sqlite:///data/olist.db") #para conectar no banco

In [25]:
df_clientes = pd.read_sql_table("tb_customers",con=engine)
df_clientes

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [26]:
df_clientes.shape

(99441, 5)

In [ ]:
#nunca puxar a tabela toda para consulta, o ideal é filtrar antes para evitar danos
query = "SELECT * FROM tb_customers LIMIT 100"
df_100 = pd.read_sql_query(query,con=engine)
df_100

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
95,f89c1a6b9c966869e441e55bc14acddc,809353196a0456095716566dd226bb48,13569,sao carlos,SP
96,23e96758fd640560e9b1fbcda90abfc4,9e1f719fe5b17b9c51905fee6d6385c1,5565,sao paulo,SP
97,369708cabd9831ea6fde670a3b602a92,94b731a41867b47c3856e324840c4c99,3636,sao paulo,SP
98,5f8b4882b5a4ec7bf6d2107e6cd0cf29,694cb45ff29b603ac2acd51016770097,24120,niteroi,RJ
99,ad6891a1937cb8723a2c08ba1ae59873,9dbb05f5577e862337b93feb8f358839,65058,sao luis,MA