In [1]:
import pandas as pd
df = pd.read_csv("data/transacoes.csv", sep=";")
df.head()

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch

In [4]:
#filtrando
filtro = (df["QtdePontos"] >=50) & (df["QtdePontos"] >100) #serie do type bool
df[filtro].head()

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
499,0066a807-064f-45a1-b5fc-21a04594d790,c52fb72f-b3dc-4650-9182-b08b5ed1420a,2025-10-30 13:12:26.669,500,twitch
656,0083ee83-6e14-47b0-adc6-0056279a892a,24782f0b-4683-4f35-976a-ea21d6714ba6,2024-04-03 13:43:18.498,500,twitch
782,009b4b6e-30d1-43fa-9a37-f8a54c7c22f9,d1527845-5bae-4747-b644-0854beaeeb58,2024-04-03 12:31:15.747,500,twitch
819,00a2f350-b341-4d01-b098-fee4184d7052,02bfd4d9-4dd6-44e5-88b8-2cc08caf3267,2024-10-04 12:36:07.021,500,twitch
911,00b8aaa0-04ff-4774-bfbf-7960e6e99d17,00a6d4c8-38e5-4e92-981e-4e4ac5084546,2024-05-27 13:58:22.229,500,twitch

In [9]:
#pontos entre 0 e 50 ou do ano de 2025 pra frente
filtro = (df["QtdePontos"] > 0) & (df["QtdePontos"] <=50) | (df["DtCriacao"] >= '2025-01-01')

df[filtro].head()

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch

In [ ]:
df_transacao_produto = pd.read_csv("data/transacao_produto.csv", sep=";")

# filtro = (df_transacao_produto["IdProduto"] == "5") | (df_transacao_produto["IdProduto"] == "11")
# df_transacao_produto[filtro]
df_transacao_produto.info()

filtro = df_transacao_produto["IdProduto"].isin(["5", "11"]) #filtro com isin 
df_transacao_produto[filtro]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302584 entries, 0 to 302583
Data columns (total 5 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   idTransacaoProduto  302584 non-null  object
 1   IdTransacao         302584 non-null  object
 2   IdProduto           302426 non-null  object
 3   QtdeProduto         302584 non-null  int64
 4   vlProduto           302584 non-null  int64
dtypes: int64(2), object(3)
memory usage: 11.5+ MB

,idTransacaoProduto,IdTransacao,IdProduto,QtdeProduto,vlProduto
0,000026d0-4d4e-4fed-934a-9e5b26d9e379,d59d9859-8fb9-41cc-a296-be38c4dce8e4,5,1,1
1,00002f54-dd03-4b3f-ade0-22c3e61df8c2,519241fd-2676-49b2-8e74-0acc09a08f69,5,1,1
2,00006a7d-c83a-44ca-aad9-e8a2a2f1b64d,73993c42-d18f-4f51-82c4-25e13c29962c,11,1,50
3,0000991a-e6ae-4b9f-8747-c6cfe77890dd,db341350-16e4-49ea-96d4-c3e991e7c8c0,5,1,1
4,0000d145-c8b5-48fb-9ea3-d91eba3af306,7ee57139-6183-4cd6-8960-b5b14884aefb,5,1,1
...,...,...,...,...,...
302579,fffd9569-31e6-4515-8494-4edeabc0cfc2,6baf63b1-d05a-419d-a84f-abdf6906fef8,11,1,50
302580,fffe7e68-c450-4025-9469-e5cbe7699b49,90f7149b-5794-4d49-9239-c3bddb5b0980,5,1,1
302581,fffead0f-105b-4517-ac6f-b60ffd66f0dd,a5240b8c-c015-4d4c-8e34-2e81973ad084,5,1,1
302582,ffff210a-2594-42fa-8d85-c97483817542,4d7c74c0-5ca0-4786-823b-b393d505c2e6,5,1,1
302583,ffff2827-d194-42ac-8a62-90b1a745eddf,410a177d-1234-4a0f-b1e2-456db06a99ba,5,1,1

In [ ]:
clientes = pd.read_csv("data/clientes.csv", sep=";")
clientes.head()

filtro = clientes["DtCriacao"].notna()
clientes[filtro]

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551
...,...,...,...,...,...,...,...,...,...
5066,ff2cabd3-3316-4b3f-8494-c25f95e90524,0,1,0,0,0,57,2025-02-10 11:12:30.631,2025-02-10 12:37:47.892
5067,ff4909ad-4e52-4767-a6fc-0fbd76e37857,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
5068,ff5d2399-6b53-49f0-b41e-fdaaa0da172a,0,1,0,0,0,2021,2025-08-25 13:09:12.556,2026-01-30 14:43:50.139
5069,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959
5070,fff7862d-4b2c-4140-a4c5-509b48ed31b4,0,1,0,0,0,1000,2025-11-12 01:01:58.698,2025-11-12 01:02:16.561

In [30]:
filtro = clientes["qtdePontos"] == 0
clientes_0 = clientes[filtro].copy()

clientes_0["flag_1"] = 1
clientes_0

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao,flag_1
5,002970bd-65c2-42bf-a17d-2bc5e95e2f0b,0,1,0,0,0,0,2025-07-16 09:36:45.831,2025-07-16 09:36:45.831,1
7,00417bdf-844f-40bf-92e1-d663373cbbd2,0,1,0,0,0,0,2025-11-10 03:14:09.875,2025-11-10 03:14:09.875,1
8,00684343-40b5-4ce7-b2e8-71a5340973bf,0,0,0,0,0,0,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000,1
10,007b8e64-a244-4404-8992-3b8098b33ccc,0,1,0,0,0,0,2025-06-10 16:13:43.144,2025-06-10 16:13:43.144,1
11,00942a67-2ffd-4afe-a10e-3caf6e950e0f,0,1,0,0,0,0,2025-10-20 22:16:31.357,2025-10-20 22:16:31.357,1
...,...,...,...,...,...,...,...,...,...,...
5052,fe7cba1d-c594-4776-9f7f-c32aebf2404f,0,1,0,0,0,0,2025-12-07 16:25:09.216,2025-12-07 16:25:09.216,1
5054,fe830a3f-5dcb-4273-ad43-465aeeb3a460,0,1,0,0,0,0,2025-10-24 17:18:33.447,2025-10-24 17:18:33.447,1
5056,fea95103-cef1-4bf4-9b72-3af3191e8705,0,1,0,0,0,0,2025-10-31 12:21:28.962,2025-10-31 12:21:28.962,1
5057,feaf434b-e428-4445-a86e-6218c40d55ae,0,1,0,0,0,0,2025-07-08 05:14:32.687,2025-07-08 05:14:32.687,1
5069,ff8d55dc-64fa-40de-992a-04a4155f5634,0,1,0,0,0,0,2025-07-12 13:50:37.959,2025-07-12 13:50:37.959,1

## Novas colunas

In [ ]:
clientes["pontos_100"]= clientes["qtdePontos"] + 100
clientes["emailTwitch"] = clientes["flEmail"] | clientes["flTwitch"]
clientes["qtdeSocial"] = clientes["flEmail"] +	clientes["flTwitch"] +	clientes["flYouTube"] + clientes["flBlueSky"] + clientes["flInstagram"]

clientes.head()

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao,pontos_100,emailTwitch,qtdeSocial
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364,102,1,1
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697,25186,0,0
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000,150,0,0
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000,102,0,0
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551,1200,1,3

In [38]:
clientes["qtdePontos"].describe()

count     5071.000000
mean       432.868073
std       1266.422932
min          0.000000
25%          0.000000
50%         53.000000
75%        300.500000
max      28221.000000
Name: qtdePontos, dtype: float64