In [2]:
import pandas as pd 
df = pd.read_csv("data/clientes.csv", sep=";")

df.sort_values(by="qtdePontos", ascending = False).head()

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
489,163022e8-12b8-486f-8604-57d8fa0ed7e1,0,1,0,0,0,28221,2025-02-19 13:11:26.517,2026-03-06 12:46:27.770
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
877,2a9d4ba3-4c58-47f9-8dc4-6f9cb50be1b1,1,1,0,0,0,23946,2025-03-07 12:59:11.756,2026-03-06 12:02:29.796
4320,d7f7eb75-4f0b-4d15-960d-8efe5ca7dd7e,0,0,0,0,0,22428,2025-03-07 12:36:50.254,2026-03-06 12:04:12.608
2550,803debdb-8136-4cb5-af29-dcd8db36bf2c,0,1,0,0,0,16246,2025-02-28 13:19:26.475,2025-07-02 13:44:45.438

In [ ]:
brinquedo = pd.DataFrame ({
    "nome": ["teo", "ana", "maria"],
    "idade":["33","27","32"],
    "salario": ["2234","2355", "6464"]
    }
)
#ordenando
brinquedo.sort_values(by=["salario", "idade"], ascending=[False, True])

    nome idade salario
2  maria    32    6464
1    ana    27    2355
0    teo    33    2234