In [2]:
import pandas as pd

df = pd.read_csv("homicidios_consolidado.csv", sep=";")
df.head()

,nome,período,homicidios-nao-negros,homicidios-de-jovens-mulheres,homicidios-de-homens-por-armas-de-fogo,homicidios,homicidios-de-jovens-homens,homicidios-negros,homicidios-de-mulheres-por-armas-de-fogo,homicidios-por-armas-de-fogo,homicidios-homens,homicidios-mulheres-nao-negras,homicidios-homens-negros,homicidios-mulheres-negras,homicidio-de-jovens-por-armas-de-fogo,homicidios-de-jovens,homicidios-mulheres
0,AC,1979,NaN,0,NaN,NaN,14,NaN,NaN,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AL,1979,NaN,6,NaN,NaN,104,NaN,NaN,131,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AM,1979,NaN,4,NaN,NaN,80,NaN,NaN,55,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AP,1979,NaN,1,NaN,NaN,7,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BA,1979,NaN,17,NaN,NaN,114,NaN,NaN,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_stack = (df.set_index(["nome","período"]).stack().reset_index())

df_stack.columns = ["nome", "periodo", "metrica", "valor"]
df_stack

      nome  periodo                                metrica  valor
0       AC     1979          homicidios-de-jovens-mulheres    0.0
1       AC     1979            homicidios-de-jovens-homens   14.0
2       AC     1979           homicidios-por-armas-de-fogo   13.0
3       AL     1979          homicidios-de-jovens-mulheres    6.0
4       AL     1979            homicidios-de-jovens-homens  104.0
...    ...      ...                                    ...    ...
13225   TO     2021               homicidios-homens-negros  333.0
13226   TO     2021             homicidios-mulheres-negras   22.0
13227   TO     2021  homicidio-de-jovens-por-armas-de-fogo  135.0
13228   TO     2021                   homicidios-de-jovens  211.0
13229   TO     2021                    homicidios-mulheres   39.0

[13230 rows x 4 columns]

In [4]:
df_stack.pivot_table(values="valor",index=["nome","periodo"],columns="metrica")

metrica       homicidio-de-jovens-por-armas-de-fogo  homicidios  \
nome periodo
AC   1979                                       NaN         NaN
     1980                                       NaN         NaN
     1981                                       NaN         NaN
     1982                                       NaN         NaN
     1983                                       NaN         NaN
...                                             ...         ...
TO   2017                                     195.0       557.0
     2018                                     191.0       570.0
     2019                                     150.0       456.0
     2020                                     164.0       484.0
     2021                                     135.0       441.0

metrica       homicidios-de-homens-por-armas-de-fogo  homicidios-de-jovens  \
nome periodo
AC   1979                                        NaN                   NaN
     1980                                        NaN                   NaN
     1981                                        NaN                   NaN
     1982                                        NaN                   NaN
     1983                                        NaN                   NaN
...                                              ...                   ...
TO   2017                                      376.0                 303.0
     2018                                      308.0                 296.0
     2019                                      237.0                 224.0
     2020                                      232.0                 246.0
     2021                                      178.0                 211.0

metrica       homicidios-de-jovens-homens  homicidios-de-jovens-mulheres  \
nome periodo
AC   1979                            14.0                            0.0
     1980                            14.0                            2.0
     1981                            13.0                            1.0
     1982                            16.0                            2.0
     1983                            16.0                            3.0
...                                   ...                            ...
TO   2017                           282.0                           21.0
     2018                           278.0                           18.0
     2019                           211.0                           13.0
     2020                           231.0                           15.0
     2021                           199.0                           12.0

metrica       homicidios-de-mulheres-por-armas-de-fogo  homicidios-homens  \
nome periodo
AC   1979                                          NaN                NaN
     1980                                          NaN                NaN
     1981                                          NaN                NaN
     1982                                          NaN                NaN
     1983                                          NaN                NaN
...                                                ...                ...
TO   2017                                         18.0              517.0
     2018                                         19.0              520.0
     2019                                         16.0              420.0
     2020                                         16.0              448.0
     2021                                         14.0              401.0

metrica       homicidios-homens-negros  homicidios-mulheres  \
nome periodo
AC   1979                          NaN                  NaN
     1980                          NaN                  NaN
     1981                          NaN                  NaN
     1982                          NaN                  NaN
     1983                          NaN                  NaN
...                                ...                  ...
TO   2017                        407.0                 38.0
     2018                        430.0                 47.0
     2019                        337.0                 36.0
     2020                        370.0                 35.0
     2021                        333.0                 39.0

metrica       homicidios-mulheres-nao-negras  homicidios-mulheres-negras  \
nome periodo
AC   1979                                NaN                         NaN
     1980                                NaN                         NaN
     1981                                NaN                         NaN
     1982                                NaN                         NaN
     1983                                NaN                         NaN
...                                      ...                         ...
TO   2017                                7.0                        30.0
     2018                                9.0                        36.0
     2019                                3.0                        32.0
     2020                                6.0                        29.0
     2021                               13.0                        22.0

metrica       homicidios-nao-negros  homicidios-negros  \
nome periodo
AC   1979                       NaN                NaN
     1980                       NaN                NaN
     1981                       NaN                NaN
     1982                       NaN                NaN
     1983                       NaN                NaN
...                             ...                ...
TO   2017                     103.0              437.0
     2018                      90.0              466.0
     2019                      76.0              369.0
     2020                      76.0              399.0
     2021                      70.0              355.0

metrica       homicidios-por-armas-de-fogo
nome periodo
AC   1979                             13.0
     1980                             12.0
     1981                              8.0
     1982                             18.0
     1983                             12.0
...                                    ...
TO   2017                            318.0
     2018                            321.0
     2019                            250.0
     2020                            278.0
     2021                            253.0

[1161 rows x 15 columns]

In [5]:
(df_stack.pivot_table(values="valor",index=["nome","periodo"],columns="metrica").reset_index())

metrica,nome,periodo,homicidio-de-jovens-por-armas-de-fogo,homicidios,homicidios-de-homens-por-armas-de-fogo,homicidios-de-jovens,homicidios-de-jovens-homens,homicidios-de-jovens-mulheres,homicidios-de-mulheres-por-armas-de-fogo,homicidios-homens,homicidios-homens-negros,homicidios-mulheres,homicidios-mulheres-nao-negras,homicidios-mulheres-negras,homicidios-nao-negros,homicidios-negros,homicidios-por-armas-de-fogo
0,AC,1979,NaN,NaN,NaN,NaN,14.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0
1,AC,1980,NaN,NaN,NaN,NaN,14.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0
2,AC,1981,NaN,NaN,NaN,NaN,13.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
3,AC,1982,NaN,NaN,NaN,NaN,16.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0
4,AC,1983,NaN,NaN,NaN,NaN,16.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1156,TO,2017,195.0,557.0,376.0,303.0,282.0,21.0,18.0,517.0,407.0,38.0,7.0,30.0,103.0,437.0,318.0
1157,TO,2018,191.0,570.0,308.0,296.0,278.0,18.0,19.0,520.0,430.0,47.0,9.0,36.0,90.0,466.0,321.0
1158,TO,2019,150.0,456.0,237.0,224.0,211.0,13.0,16.0,420.0,337.0,36.0,3.0,32.0,76.0,369.0,250.0
1159,TO,2020,164.0,484.0,232.0,246.0,231.0,15.0,16.0,448.0,370.0,35.0,6.0,29.0,76.0,399.0,278.0
1160,TO,2021,135.0,441.0,178.0,211.0,199.0,12.0,14.0,401.0,333.0,39.0,13.0,22.0,70.0,355.0,253.0

In [6]:
df_stack.pivot_table(values="valor",index=["nome"],columns="metrica",aggfunc="mean")

metrica,homicidio-de-jovens-por-armas-de-fogo,homicidios,homicidios-de-homens-por-armas-de-fogo,homicidios-de-jovens,homicidios-de-jovens-homens,homicidios-de-jovens-mulheres,homicidios-de-mulheres-por-armas-de-fogo,homicidios-homens,homicidios-homens-negros,homicidios-mulheres,homicidios-mulheres-nao-negras,homicidios-mulheres-negras,homicidios-nao-negros,homicidios-negros,homicidios-por-armas-de-fogo
nome,,,,,,,,,,,,,,,
AC,53.545455,173.636364,86.151515,93.000000,70.302326,6.558140,6.484848,156.272727,127.461538,16.969697,4.115385,12.153846,30.538462,139.615385,76.232558
AL,575.606061,1249.242424,508.393939,703.757576,551.930233,33.558140,49.393939,1165.878788,1061.307692,83.000000,5.730769,67.346154,56.692308,1128.730769,791.209302
AM,296.696970,848.454545,1239.666667,486.696970,370.953488,24.558140,25.909091,783.454545,790.538462,64.272727,12.153846,58.769231,89.115385,849.384615,384.186047
AP,64.636364,209.636364,49.727273,132.939394,99.953488,5.186047,5.363636,195.727273,201.769231,13.848485,1.807692,12.730769,15.769231,214.500000,76.906977
BA,1698.545455,3651.878788,340.606061,2149.000000,1603.581395,94.883721,144.303030,3386.303030,3391.038462,259.515152,29.384615,235.884615,271.730769,3627.884615,2109.813953
CE,958.333333,2169.939394,208.515152,1219.000000,928.511628,59.953488,95.727273,2010.181818,1569.846154,159.030303,21.500000,119.153846,201.807692,1689.038462,1241.325581
DF,294.424242,649.818182,705.303030,371.090909,290.000000,20.953488,28.575758,595.272727,509.038462,54.060606,12.192308,40.923077,99.846154,550.153846,369.697674
ES,611.757576,1424.303030,374.848485,767.454545,580.767442,50.093023,74.575758,1288.272727,869.807692,134.757576,26.230769,85.692308,209.192308,955.615385,810.813953
GO,642.606061,1635.969697,1500.818182,856.181818,652.372093,58.302326,76.484848,1474.515152,1192.423077,157.939394,48.423077,105.384615,410.461538,1298.576923,886.441860
MA,367.121212,1126.030303,560.575758,574.181818,431.883721,25.837209,32.090909,1047.121212,1052.923077,77.696970,13.384615,71.923077,147.615385,1125.307692,535.348837
MG,1200.484848,2931.636364,968.303030,1549.393939,1183.418605,110.046512,133.575758,2630.181818,2086.807692,299.878788,113.038462,199.115385,916.307692,2286.038462,1592.930233
MS,172.787879,606.454545,2142.121212,269.303030,208.976744,22.372093,26.545455,541.303030,292.192308,63.969697,28.884615,29.461538,224.230769,321.653846,291.720930
MT,251.757576,852.848485,628.878788,373.575758,275.953488,26.767442,32.515152,771.515152,603.153846,79.969697,28.038462,55.692308,239.153846,659.153846,405.953488
PA,796.515152,2077.727273,517.878788,1113.424242,847.558140,54.953488,76.909091,1927.060606,2013.230769,145.787879,18.846154,140.923077,181.846154,2155.192308,1117.279070
PB,371.484848,874.575758,2342.272727,464.666667,362.581395,28.441860,43.969697,800.909091,748.923077,72.606061,9.423077,59.076923,60.653846,808.115385,533.069767
PE,1750.454545,3739.909091,1457.636364,2085.272727,1685.046512,102.325581,153.909091,3484.272727,2870.076923,251.727273,41.615385,188.346154,423.576923,3058.961538,2489.627907
PI,113.636364,361.939394,2843.000000,184.484848,138.279070,10.953488,11.969697,328.787879,319.423077,32.333333,6.423077,28.500000,46.807692,348.153846,155.465116
PR,884.878788,2330.030303,1870.727273,1193.393939,929.953488,79.325581,101.848485,2114.090909,497.230769,213.666667,176.000000,43.384615,1927.076923,540.807692,1271.232558
RJ,2645.363636,6248.272727,4547.454545,3340.242424,2738.069767,149.209302,266.575758,5786.363636,3618.076923,438.818182,162.807692,232.461538,1847.846154,3855.769231,4008.720930
RN,353.181818,741.303030,1236.787879,420.333333,319.186047,19.255814,31.575758,689.666667,660.153846,51.454545,11.461538,42.884615,114.846154,703.153846,464.325581
RO,139.515152,499.030303,289.909091,206.393939,162.348837,16.581395,21.848485,452.151515,297.076923,45.848485,14.307692,26.884615,129.692308,324.153846,268.744186
RR,25.909091,144.212121,1059.000000,65.393939,46.790698,5.534884,3.757576,126.303030,99.230769,17.545455,8.692308,9.538462,39.153846,108.807692,39.418605
RS,773.969697,2022.909091,562.090909,977.575758,763.511628,67.046512,110.393939,1820.636364,408.153846,201.303030,169.730769,34.346154,1624.000000,442.500000,1180.511628
SC,187.606061,630.151515,269.363636,289.969697,223.511628,25.139535,29.090909,554.727273,109.346154,75.151515,63.961538,11.615385,520.730769,120.961538,296.116279
SE,2335.757576,618.969697,917.939394,339.212121,254.348837,12.697674,20.575758,579.303030,549.153846,38.575758,6.307692,30.692308,60.307692,579.923077,361.790698
SP,2719.848485,8783.909091,1794.848485,4702.272727,4062.651163,298.395349,285.636364,8041.878788,3072.307692,738.393939,428.884615,234.884615,4339.846154,3307.692308,3920.744186
TO,69.181818,259.848485,319.969697,124.515152,87.000000,8.534884,9.393939,233.272727,212.615385,25.969697,5.884615,22.269231,57.115385,234.961538,99.279070