In [3]:
import pandas as pd

df = pd.read_csv("homicidios_consolidado.csv", sep=";")
df.head()

,nome,período,homicidios-nao-negros,homicidios-de-jovens-mulheres,homicidios-de-homens-por-armas-de-fogo,homicidios,homicidios-de-jovens-homens,homicidios-negros,homicidios-de-mulheres-por-armas-de-fogo,homicidios-por-armas-de-fogo,homicidios-homens,homicidios-mulheres-nao-negras,homicidios-homens-negros,homicidios-mulheres-negras,homicidio-de-jovens-por-armas-de-fogo,homicidios-de-jovens,homicidios-mulheres
0,AC,1979,NaN,0,NaN,NaN,14,NaN,NaN,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AL,1979,NaN,6,NaN,NaN,104,NaN,NaN,131,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AM,1979,NaN,4,NaN,NaN,80,NaN,NaN,55,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AP,1979,NaN,1,NaN,NaN,7,NaN,NaN,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BA,1979,NaN,17,NaN,NaN,114,NaN,NaN,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df = df.reset_index()
# df =df.set_index (["nome", "período"])
# df_stack =df.stack()
# df_stack.head()

In [11]:
df = df.set_index(["nome", "período"])
df_stack = df.stack()
df_stack.head()

nome  período
AC    1979     homicidios-de-jovens-mulheres      0.0
               homicidios-de-jovens-homens       14.0
               homicidios-por-armas-de-fogo      13.0
AL    1979     homicidios-de-jovens-mulheres      6.0
               homicidios-de-jovens-homens      104.0
dtype: float64

In [12]:
df_stack = df_stack.reset_index()

In [13]:
df_stack.columns = ["nome", "período", "metrica", "valor"]
df_stack.head()

  nome  período                        metrica  valor
0   AC     1979  homicidios-de-jovens-mulheres    0.0
1   AC     1979    homicidios-de-jovens-homens   14.0
2   AC     1979   homicidios-por-armas-de-fogo   13.0
3   AL     1979  homicidios-de-jovens-mulheres    6.0
4   AL     1979    homicidios-de-jovens-homens  104.0

In [14]:
df_unstack = (df_stack.set_index(["nome", "período", "metrica"]).unstack().reset_index())
df_unstack

        nome período                                 valor             \
metrica              homicidio-de-jovens-por-armas-de-fogo homicidios
0         AC    1979                                   NaN        NaN
1         AC    1980                                   NaN        NaN
2         AC    1981                                   NaN        NaN
3         AC    1982                                   NaN        NaN
4         AC    1983                                   NaN        NaN
...      ...     ...                                   ...        ...
1156      TO    2017                                 195.0      557.0
1157      TO    2018                                 191.0      570.0
1158      TO    2019                                 150.0      456.0
1159      TO    2020                                 164.0      484.0
1160      TO    2021                                 135.0      441.0

                                                                     \
metrica homicidios-de-homens-por-armas-de-fogo homicidios-de-jovens
0                                          NaN                  NaN
1                                          NaN                  NaN
2                                          NaN                  NaN
3                                          NaN                  NaN
4                                          NaN                  NaN
...                                        ...                  ...
1156                                     376.0                303.0
1157                                     308.0                296.0
1158                                     237.0                224.0
1159                                     232.0                246.0
1160                                     178.0                211.0

                                                                   \
metrica homicidios-de-jovens-homens homicidios-de-jovens-mulheres
0                              14.0                           0.0
1                              14.0                           2.0
2                              13.0                           1.0
3                              16.0                           2.0
4                              16.0                           3.0
...                             ...                           ...
1156                          282.0                          21.0
1157                          278.0                          18.0
1158                          211.0                          13.0
1159                          231.0                          15.0
1160                          199.0                          12.0

                                                                    \
metrica homicidios-de-mulheres-por-armas-de-fogo homicidios-homens
0                                            NaN               NaN
1                                            NaN               NaN
2                                            NaN               NaN
3                                            NaN               NaN
4                                            NaN               NaN
...                                          ...               ...
1156                                        18.0             517.0
1157                                        19.0             520.0
1158                                        16.0             420.0
1159                                        16.0             448.0
1160                                        14.0             401.0

                                                      \
metrica homicidios-homens-negros homicidios-mulheres
0                            NaN                 NaN
1                            NaN                 NaN
2                            NaN                 NaN
3                            NaN                 NaN
4                            NaN                 NaN
...                          ...                 ...
1156                       407.0                38.0
1157                       430.0                47.0
1158                       337.0                36.0
1159                       370.0                35.0
1160                       333.0                39.0

                                                                   \
metrica homicidios-mulheres-nao-negras homicidios-mulheres-negras
0                                  NaN                        NaN
1                                  NaN                        NaN
2                                  NaN                        NaN
3                                  NaN                        NaN
4                                  NaN                        NaN
...                                ...                        ...
1156                               7.0                       30.0
1157                               9.0                       36.0
1158                               3.0                       32.0
1159                               6.0                       29.0
1160                              13.0                       22.0


metrica homicidios-nao-negros homicidios-negros homicidios-por-armas-de-fogo
0                         NaN               NaN                         13.0
1                         NaN               NaN                         12.0
2                         NaN               NaN                          8.0
3                         NaN               NaN                         18.0
4                         NaN               NaN                         12.0
...                       ...               ...                          ...
1156                    103.0             437.0                        318.0
1157                     90.0             466.0                        321.0
1158                     76.0             369.0                        250.0
1159                     76.0             399.0                        278.0
1160                     70.0             355.0                        253.0

[1161 rows x 17 columns]

In [ ]:
metricas = df_unstack.columns.droplevel(0)[2:].to_list() #excluindo multi-index
df_unstack.columns = ["nome", "período"] + metricas
df_unstack

,nome,período,homicidio-de-jovens-por-armas-de-fogo,homicidios,homicidios-de-homens-por-armas-de-fogo,homicidios-de-jovens,homicidios-de-jovens-homens,homicidios-de-jovens-mulheres,homicidios-de-mulheres-por-armas-de-fogo,homicidios-homens,homicidios-homens-negros,homicidios-mulheres,homicidios-mulheres-nao-negras,homicidios-mulheres-negras,homicidios-nao-negros,homicidios-negros,homicidios-por-armas-de-fogo
0,AC,1979,NaN,NaN,NaN,NaN,14.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0
1,AC,1980,NaN,NaN,NaN,NaN,14.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0
2,AC,1981,NaN,NaN,NaN,NaN,13.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0
3,AC,1982,NaN,NaN,NaN,NaN,16.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.0
4,AC,1983,NaN,NaN,NaN,NaN,16.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1156,TO,2017,195.0,557.0,376.0,303.0,282.0,21.0,18.0,517.0,407.0,38.0,7.0,30.0,103.0,437.0,318.0
1157,TO,2018,191.0,570.0,308.0,296.0,278.0,18.0,19.0,520.0,430.0,47.0,9.0,36.0,90.0,466.0,321.0
1158,TO,2019,150.0,456.0,237.0,224.0,211.0,13.0,16.0,420.0,337.0,36.0,3.0,32.0,76.0,369.0,250.0
1159,TO,2020,164.0,484.0,232.0,246.0,231.0,15.0,16.0,448.0,370.0,35.0,6.0,29.0,76.0,399.0,278.0
1160,TO,2021,135.0,441.0,178.0,211.0,199.0,12.0,14.0,401.0,333.0,39.0,13.0,22.0,70.0,355.0,253.0